# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190404_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerelation',
            name='relation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
